// Spanish municipalities — provincial capitals plus the most populous towns
// across all 50 provinces. Used by the Sarevi simulator's searchable Municipio
// select; the simulator demos a typeahead UX that scales to thousands of
// entries without a paginated dropdown.
//
// Order: alphabetical (default Spanish collation). Names include accents and
// the slash form for bilingual municipalities (e.g. "Donostia / San
// Sebastián"). Not exhaustive — extend as needed when real product data lands.

export const MUNICIPIOS_ES: readonly string[] = [
  'A Coruña',
  'Adeje',
  'Aguilar de Campoo',
  'Alaquàs',
  'Alarcón',
  'Albacete',
  'Alcalá de Guadaíra',
  'Alcalá de Henares',
  'Alcalá la Real',
  'Alcantarilla',
  'Alcázar de San Juan',
  'Alcobendas',
  'Alcorcón',
  'Alcoy / Alcoi',
  'Aldaia',
  'Alfafar',
  'Algeciras',
  'Algemesí',
  'Alhama de Murcia',
  'Alicante / Alacant',
  'Almería',
  'Almuñécar',
  'Alzira',
  'Andújar',
  'Antequera',
  'Aranda de Duero',
  'Aranjuez',
  'Arcos de la Frontera',
  'Arona',
  'Arrasate / Mondragón',
  'Arrecife',
  'Arroyomolinos',
  'Astorga',
  'Atarfe',
  'Avilés',
  'Aínsa-Sobrarbe',
  'Ávila',
  'Badajoz',
  'Badalona',
  'Baeza',
  'Baracaldo / Barakaldo',
  'Barbastro',
  'Barcelona',
  'Basauri',
  'Baza',
  'Béjar',
  'Benalmádena',
  'Benavente',
  'Benetússer',
  'Benicarló',
  'Benicàssim',
  'Benidorm',
  'Bermeo',
  'Berriozar',
  'Betanzos',
  'Bilbao',
  'Boadilla del Monte',
  'Boiro',
  'Burgos',
  'Burjassot',
  'Burlada / Burlata',
  'Cabra',
  'Cáceres',
  'Cádiz',
  'Calahorra',
  'Calatayud',
  'Caldes de Montbui',
  'Calpe / Calp',
  'Cambados',
  'Cambrils',
  'Campello (El) / Campello',
  'Campo de Criptana',
  'Cangas',
  'Cangas del Narcea',
  'Carballo',
  'Carcaixent',
  'Carmona',
  'Cartagena',
  'Castellón de la Plana / Castelló de la Plana',
  'Castro-Urdiales',
  'Castuera',
  'Catarroja',
  'Cee',
  'Cehegín',
  'Ceuta',
  'Chiclana de la Frontera',
  'Chipiona',
  'Ciempozuelos',
  'Cieza',
  'Ciudad Real',
  'Ciudad Rodrigo',
  'Coín',
  'Collado Villalba',
  'Colmenar Viejo',
  'Córdoba',
  'Cornellà de Llobregat',
  'Coslada',
  'Cuenca',
  'Cuevas del Almanzora',
  'Cullera',
  'Daimiel',
  'Dénia',
  'Don Benito',
  'Donostia / San Sebastián',
  'Dos Hermanas',
  'Durango',
  'Écija',
  'Eibar',
  'Eivissa',
  'Ejea de los Caballeros',
  'Elche / Elx',
  'Elda',
  'Elgoibar',
  'Erandio',
  'Errenteria',
  'Esplugues de Llobregat',
  'Estepona',
  'Ferrol',
  'Figueres',
  'Fraga',
  'Fuengirola',
  'Fuenlabrada',
  'Galdakao',
  'Gandía',
  'Getafe',
  'Getxo',
  'Gijón / Xixón',
  'Girona',
  'Granada',
  'Granollers',
  'Guadalajara',
  'Guadix',
  'Guardamar del Segura',
  'Guernica / Gernika-Lumo',
  'Haro',
  'Hellín',
  'Hernani',
  'Huelva',
  'Huesca',
  'Huércal-Overa',
  'Igualada',
  'Illescas',
  'Inca',
  'Irún',
  'Iruña / Pamplona',
  'Jaca',
  'Jaén',
  'Jerez de la Frontera',
  'Jumilla',
  'Játiva / Xàtiva',
  'L\'Eliana',
  'L\'Hospitalet de Llobregat',
  'La Algaba',
  'La Bañeza',
  'La Línea de la Concepción',
  'La Orotava',
  'La Pobla de Vallbona',
  'La Roda',
  'Laguna de Duero',
  'Lalín',
  'Langreo',
  'Las Palmas de Gran Canaria',
  'Las Rozas de Madrid',
  'Lebrija',
  'Leganés',
  'León',
  'Lepe',
  'Liria / Llíria',
  'Lloret de Mar',
  'Logroño',
  'Loja',
  'Lorca',
  'Los Llanos de Aridane',
  'Los Realejos',
  'Lucena',
  'Lugo',
  'Madrid',
  'Mahón / Maó',
  'Mairena del Aljarafe',
  'Majadahonda',
  'Málaga',
  'Manacor',
  'Manises',
  'Manresa',
  'Manzanares',
  'Marbella',
  'Martos',
  'Mataró',
  'Medina del Campo',
  'Melilla',
  'Mérida',
  'Mieres',
  'Mijas',
  'Miranda de Ebro',
  'Mislata',
  'Molina de Segura',
  'Mollet del Vallès',
  'Moncada',
  'Monforte de Lemos',
  'Montilla',
  'Mora',
  'Morón de la Frontera',
  'Móstoles',
  'Motril',
  'Mungia',
  'Murcia',
  'Mutxamel',
  'Mutriku',
  'Náquera',
  'Navalcarnero',
  'Nerja',
  'Níjar',
  'Noia',
  'Olivenza',
  'Olot',
  'Ondarroa',
  'Ontinyent',
  'Orihuela',
  'Ourense',
  'Oviedo',
  'Palafrugell',
  'Palencia',
  'Palma',
  'Palma del Río',
  'Paterna',
  'Petrer',
  'Pinto',
  'Pizarra',
  'Plasencia',
  'Ponferrada',
  'Pontevedra',
  'Portugalete',
  'Pozoblanco',
  'Pozuelo de Alarcón',
  'Priego de Córdoba',
  'Puente Genil',
  'Puerto de la Cruz',
  'Puerto del Rosario',
  'Puerto Real',
  'Puertollano',
  'Punta Umbría',
  'Quart de Poblet',
  'Reinosa',
  'Reus',
  'Rinconada (La)',
  'Ripollet',
  'Ronda',
  'Roquetas de Mar',
  'Rota',
  'Rubí',
  'Sabadell',
  'Sagunto / Sagunt',
  'Salamanca',
  'Salou',
  'Salt',
  'San Andrés del Rabanedo',
  'San Bartolomé de Tirajana',
  'San Cristóbal de La Laguna',
  'San Fernando',
  'San Fernando de Henares',
  'San Javier',
  'San Lorenzo de El Escorial',
  'San Pedro del Pinatar',
  'San Roque',
  'San Sebastián de los Reyes',
  'San Vicente del Raspeig',
  'Sanlúcar de Barrameda',
  'Sant Adrià de Besòs',
  'Sant Boi de Llobregat',
  'Sant Cugat del Vallès',
  'Sant Feliu de Llobregat',
  'Sant Joan d\'Alacant',
  'Sant Pere de Ribes',
  'Sant Vicenç dels Horts',
  'Santa Coloma de Gramenet',
  'Santa Cruz de Tenerife',
  'Santa Eulària des Riu',
  'Santa Lucía de Tirajana',
  'Santa Marta de Tormes',
  'Santa Perpètua de Mogoda',
  'Santa Pola',
  'Santander',
  'Santiago de Compostela',
  'Santoña',
  'Santurtzi',
  'Sariñena',
  'Segovia',
  'Sestao',
  'Sevilla',
  'Siero',
  'Silla',
  'Sitges',
  'Sondika',
  'Soria',
  'Sueca',
  'Talavera de la Reina',
  'Tarancón',
  'Tarazona',
  'Tarragona',
  'Telde',
  'Teruel',
  'Toledo',
  'Tolosa',
  'Torre-Pacheco',
  'Torrejón de Ardoz',
  'Torrelavega',
  'Torrelodones',
  'Torremolinos',
  'Torrent',
  'Torrevieja',
  'Tortosa',
  'Totana',
  'Tres Cantos',
  'Tudela',
  'Turís',
  'Úbeda',
  'Utebo',
  'Utrera',
  'Valdemoro',
  'Valdepeñas',
  'Valencia / València',
  'Valencia de Don Juan',
  'Valladolid',
  'Vall d\'Uixó (La)',
  'Vélez-Málaga',
  'Vendrell (El)',
  'Vera',
  'Viana',
  'Vic',
  'Vícar',
  'Vigo',
  'Vila-real',
  'Vilafranca del Penedès',
  'Vilagarcía de Arousa',
  'Vilanova i la Geltrú',
  'Villacarrillo',
  'Villaviciosa de Odón',
  'Villena',
  'Vinaròs',
  'Viladecans',
  'Vitoria-Gasteiz',
  'Viveiro',
  'Yecla',
  'Zafra',
  'Zamora',
  'Zaragoza',
  'Zarautz',
  'Zumaia',
];
