# azure-pipelines.yml

trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  azureSubscription: 'Azure Dev/Pre'
  appName: 'afi-designsystem-as'
  nodeVersion: '24.x'
  distFolder: 'dist/app'

stages:
- stage: BuildAndDeploy
  displayName: Build and deploy Angular
  jobs:
  - job: BuildAndDeploy
    displayName: Build and deploy
    steps:
    - task: UseNode@1
      displayName: Use Node.js
      inputs:
        version: '$(nodeVersion)'

    - script: npm ci
      displayName: Install dependencies

    - script: npm run build -- --configuration coherence-site
      displayName: Build Angular

    - task: ArchiveFiles@2
      displayName: Archive Angular dist
      inputs:
        rootFolderOrFile: '$(distFolder)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: '$(Build.ArtifactStagingDirectory)/angular-app.zip'
        replaceExistingArchive: true

    - task: AzureWebApp@1
      displayName: Deploy to Azure App Service
      inputs:
        azureSubscription: '$(azureSubscription)'
        appType: webApp
        appName: '$(appName)'
        package: '$(Build.ArtifactStagingDirectory)/angular-app.zip'