/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './apps/site/src/**/*.{html,ts}',
    './libs/ui/**/*.{html,ts}',
  ],
  theme: {
    extend: {
      colors: {
        canvas: {
          base:           'var(--canvas-base)',
          fg:             'var(--canvas-fg)',
          'fg-muted':     'var(--canvas-fg-muted)',
          'fg-on-action': 'var(--canvas-fg-on-action)',
        },
        surface: {
          DEFAULT:  'var(--surface-base)',
          base:     'var(--surface-base)',
          quiet:    'var(--surface-quiet)',
          muted:    'var(--surface-muted)',
          elevated: 'var(--surface-elevated)',
          overlay:  'var(--surface-overlay)',
        },
        action: {
          DEFAULT: 'var(--action-500)',
          50:  'var(--action-50)',
          100: 'var(--action-100)',
          200: 'var(--action-200)',
          300: 'var(--action-300)',
          400: 'var(--action-400)',
          500: 'var(--action-500)',
          600: 'var(--action-600)',
          700: 'var(--action-700)',
          800: 'var(--action-800)',
          900: 'var(--action-900)',
        },
        neutral: {
          50:  'var(--color-neutral-50)',
          100: 'var(--color-neutral-100)',
          200: 'var(--color-neutral-200)',
          300: 'var(--color-neutral-300)',
          400: 'var(--color-neutral-400)',
          500: 'var(--color-neutral-500)',
          600: 'var(--color-neutral-600)',
          700: 'var(--color-neutral-700)',
          800: 'var(--color-neutral-800)',
          900: 'var(--color-neutral-900)',
          950: 'var(--color-neutral-950)',
        },
        system: {
          error: {
            DEFAULT: 'var(--system-error-500)',
            50:  'var(--system-error-50)',
            100: 'var(--system-error-100)',
            500: 'var(--system-error-500)',
            600: 'var(--system-error-600)',
            700: 'var(--system-error-700)',
          },
          success: {
            DEFAULT: 'var(--system-success-500)',
            50:  'var(--system-success-50)',
            100: 'var(--system-success-100)',
            500: 'var(--system-success-500)',
            600: 'var(--system-success-600)',
            700: 'var(--system-success-700)',
          },
          warning: {
            DEFAULT: 'var(--system-warning-500)',
            50:  'var(--system-warning-50)',
            100: 'var(--system-warning-100)',
            500: 'var(--system-warning-500)',
            600: 'var(--system-warning-600)',
            700: 'var(--system-warning-700)',
          },
          info: {
            DEFAULT: 'var(--system-info-500)',
            50:  'var(--system-info-50)',
            100: 'var(--system-info-100)',
            500: 'var(--system-info-500)',
            600: 'var(--system-info-600)',
            700: 'var(--system-info-700)',
          },
          // Flat aliases kept for backwards compat with existing component code
          'error-base': 'var(--system-error-base, var(--system-error-500))',
          'error-bg':   'var(--system-error-bg, var(--system-error-50))',
          'error-fg':   'var(--system-error-fg, var(--system-error-700))',
          'warning-base': 'var(--system-warning-base, var(--system-warning-500))',
          'warning-bg':   'var(--system-warning-bg, var(--system-warning-50))',
          'warning-fg':   'var(--system-warning-fg, var(--system-warning-700))',
          'success-base': 'var(--system-success-base, var(--system-success-500))',
          'success-bg':   'var(--system-success-bg, var(--system-success-50))',
          'success-fg':   'var(--system-success-fg, var(--system-success-700))',
          'info-base': 'var(--system-info-base, var(--system-info-500))',
          'info-bg':   'var(--system-info-bg, var(--system-info-50))',
          'info-fg':   'var(--system-info-fg, var(--system-info-700))',
        },
        status: {
          'draft-bg':     'var(--status-draft-bg)',
          'draft-fg':     'var(--status-draft-fg)',
          'draft-dot':    'var(--status-draft-dot)',
          'pending-bg':   'var(--status-pending-bg)',
          'pending-fg':   'var(--status-pending-fg)',
          'pending-dot':  'var(--status-pending-dot)',
          'approved-bg':  'var(--status-approved-bg)',
          'approved-fg':  'var(--status-approved-fg)',
          'approved-dot': 'var(--status-approved-dot)',
          'rejected-bg':  'var(--status-rejected-bg)',
          'rejected-fg':  'var(--status-rejected-fg)',
          'rejected-dot': 'var(--status-rejected-dot)',
          'executed-bg':  'var(--status-executed-bg)',
          'executed-fg':  'var(--status-executed-fg)',
          'executed-dot': 'var(--status-executed-dot)',
          'cancelled-bg': 'var(--status-cancelled-bg)',
          'cancelled-fg': 'var(--status-cancelled-fg)',
          'cancelled-dot':'var(--status-cancelled-dot)',
          'in-review-bg': 'var(--status-in-review-bg)',
          'in-review-fg': 'var(--status-in-review-fg)',
          'in-review-dot':'var(--status-in-review-dot)',
          'archived-bg':  'var(--status-archived-bg)',
          'archived-fg':  'var(--status-archived-fg)',
          'archived-dot': 'var(--status-archived-dot)',
        },
        border: {
          hairline: 'var(--border-hairline)',
          focus:    'var(--border-focus)',
        },
        data: {
          'neutral-strong': 'var(--data-neutral-strong)',
          'neutral-medium': 'var(--data-neutral-medium)',
          'neutral-muted': 'var(--data-neutral-muted)',
          'highlight-primary': 'var(--data-highlight-primary)',
          'highlight-secondary': 'var(--data-highlight-secondary)',
          'diverge-neg-100': 'var(--data-diverge-neg-100)',
          'diverge-neg-300': 'var(--data-diverge-neg-300)',
          'diverge-neg-500': 'var(--data-diverge-neg-500)',
          'diverge-neg-700': 'var(--data-diverge-neg-700)',
          'diverge-pos-100': 'var(--data-diverge-pos-100)',
          'diverge-pos-300': 'var(--data-diverge-pos-300)',
          'diverge-pos-500': 'var(--data-diverge-pos-500)',
          'diverge-pos-700': 'var(--data-diverge-pos-700)',
          'semantic-positive': 'var(--data-semantic-positive)',
          'semantic-negative': 'var(--data-semantic-negative)',
          'semantic-warning': 'var(--data-semantic-warning)',
        },
      },
      spacing: {
        // Numeric scale — base-4 (Tailwind 1 = 4px)
        1:  'var(--dim-4, 4px)',
        2:  'var(--dim-8, 8px)',
        3:  'var(--dim-12, 12px)',
        4:  'var(--dim-16, 16px)',
        5:  'var(--dim-20, 20px)',
        6:  'var(--dim-24, 24px)',
        8:  'var(--dim-32, 32px)',
        10: 'var(--dim-40, 40px)',
        12: 'var(--dim-48, 48px)',
        14: 'var(--dim-56, 56px)',
        16: 'var(--dim-64, 64px)',
        20: 'var(--dim-80, 80px)',
        24: 'var(--dim-96, 96px)',

        // Namespaced space-* scale — SAME values, aliased under the space-N prefix.
        // This is what every Coherence spec writes: p-space-6, gap-space-4, etc.
        // Without these keys Tailwind silently drops those classes. LOCKED 2026-04-17-rev7.
        'space-0':  '0',
        'space-1':  'var(--dim-4, 4px)',
        'space-2':  'var(--dim-8, 8px)',
        'space-3':  'var(--dim-12, 12px)',
        'space-4':  'var(--dim-16, 16px)',
        'space-5':  'var(--dim-20, 20px)',
        'space-6':  'var(--dim-24, 24px)',
        'space-8':  'var(--dim-32, 32px)',
        'space-10': 'var(--dim-40, 40px)',
        'space-12': 'var(--dim-48, 48px)',
        'space-14': 'var(--dim-56, 56px)',
        'space-16': 'var(--dim-64, 64px)',
        'space-20': 'var(--dim-80, 80px)',
        'space-24': 'var(--dim-96, 96px)',
        'space-32': '128px',
      },
      borderRadius: {
        none: '0',
        sm:   'var(--radius-sm)',
        md:   'var(--radius-md)',
        lg:   'var(--radius-lg)',
        full: '9999px',
      },
      boxShadow: {
        sm: 'var(--shadow-sm, 0 1px 2px 0 rgb(0 0 0 / 0.05))',
        md: 'var(--shadow-md, 0 4px 6px -1px rgb(0 0 0 / 0.1))',
        lg: 'var(--shadow-lg, 0 10px 15px -3px rgb(0 0 0 / 0.1))',
      },
      transitionDuration: {
        DEFAULT: 'var(--duration-base, 200ms)',
        fast:    'var(--duration-fast, 150ms)',
        slow:    'var(--duration-slow, 300ms)',
      },
      transitionTimingFunction: {
        DEFAULT:       'var(--easing-standard, cubic-bezier(0.4, 0, 0.2, 1))',
        enter:         'var(--easing-enter, cubic-bezier(0.16, 1, 0.3, 1))',
        exit:          'var(--easing-exit, cubic-bezier(0.7, 0, 0.84, 0))',
        standard:      'var(--easing-standard, cubic-bezier(0.4, 0, 0.2, 1))',
        'spring-soft': 'var(--easing-spring-soft, cubic-bezier(0.34, 1.56, 0.64, 1))',
      },
      fontFamily: {
        serif: ['Roboto Serif', 'serif'],
        sans:  ['Roboto', 'sans-serif'],
        mono:  ['Roboto Mono', 'monospace'],
      },
      fontSize: {
        display:         ['96px', { lineHeight: '112px', fontWeight: '400' }],
        title:           ['32px', { lineHeight: '40px',  fontWeight: '500' }],
        subtitle:        ['24px', { lineHeight: '32px',  fontWeight: '500' }],
        section:         ['20px', { lineHeight: '24px',  fontWeight: '500' }],
        'subtitle-body': ['20px', { lineHeight: '20px',  fontWeight: '400' }],
        body:            ['16px', { lineHeight: '24px',  fontWeight: '400' }],
        'body-lg-600':   ['16px', { lineHeight: '24px',  fontWeight: '600' }],
        'body-lg-500':   ['16px', { lineHeight: '24px',  fontWeight: '500' }],
        'body-md':       ['14px', { lineHeight: '20px',  fontWeight: '400' }],
        'body-md-600':   ['14px', { lineHeight: '20px',  fontWeight: '600' }],
        'body-md-500':   ['14px', { lineHeight: '20px',  fontWeight: '500' }],
        'body-sm':       ['12px', { lineHeight: '16px',  fontWeight: '400' }],
        'body-sm-600':   ['12px', { lineHeight: '16px',  fontWeight: '600' }],
        'body-sm-500':   ['12px', { lineHeight: '16px',  fontWeight: '500' }],
        button:          ['14px', { lineHeight: '14px',  fontWeight: '500' }],
        informe:         ['12px', { lineHeight: '14px',  fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
