/**
 * Moodboard gallery slides (section 3) — the Mobbin screens we each saved.
 *
 * Order is deliberate, not the export order: Wise first (the fintech that set
 * the black-and-white-with-colour-in-data direction), then the products the
 * post names as references (Cursor, Stack AI, Clerk, Shopify, Notion, Linear),
 * then the rest of the board.
 *
 * Sources live at apps/site/public/assets/blog/visual-identity/moodboard/,
 * converted from the PNG exports in "Modern UI moodboard/".
 */
export interface MoodboardSlide {
  readonly src: string;
  readonly app: string;
}

/** Non-empty by construction, so the gallery's first slide is always defined. */
export const MOODBOARD_SLIDES: readonly [MoodboardSlide, ...MoodboardSlide[]] = [
  { src: 'assets/blog/visual-identity/moodboard/moodboard-6.jpg', app: 'Wise' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-7.jpg', app: 'Wise' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-57.jpg', app: 'Wise' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-87.jpg', app: 'Cursor' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-93.jpg', app: 'Cursor' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-104.jpg', app: 'Cursor' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-18.jpg', app: 'Stack AI' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-61.jpg', app: 'Stack AI' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-20.jpg', app: 'Clerk' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-82.jpg', app: 'Clerk' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-105.jpg', app: 'Clerk' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-33.jpg', app: 'Shopify' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-17.jpg', app: 'Notion' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-23.jpg', app: 'Notion' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-86.jpg', app: 'Notion' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-98.jpg', app: 'Notion' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-106.jpg', app: 'Notion' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-74.jpg', app: 'Linear' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-88.jpg', app: 'Linear' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-0.jpg', app: 'Jira' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-1.jpg', app: 'Modal' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-2.jpg', app: 'QuickBooks' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-3.jpg', app: 'Whop' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-4.jpg', app: 'Autosend' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-5.jpg', app: 'Autosend' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-8.jpg', app: 'Base44' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-9.jpg', app: 'Clay' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-10.jpg', app: 'ElevenLabs' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-11.jpg', app: 'Resend' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-12.jpg', app: 'Ferndesk' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-13.jpg', app: 'Zoho CRM' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-14.jpg', app: 'Cloudflare' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-15.jpg', app: 'Arcade' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-16.jpg', app: 'Claude' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-19.jpg', app: 'Vercel' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-21.jpg', app: 'Langdock' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-22.jpg', app: 'Vercel' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-24.jpg', app: 'Vercel' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-25.jpg', app: 'Obvious' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-26.jpg', app: 'Obvious' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-27.jpg', app: 'komoot' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-28.jpg', app: 'Open' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-29.jpg', app: 'Sprig' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-30.jpg', app: 'Manus' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-31.jpg', app: 'Apollo' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-32.jpg', app: 'Modal' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-34.jpg', app: 'Laravel Cloud' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-35.jpg', app: 'Alan' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-36.jpg', app: 'Cloudflare' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-37.jpg', app: 'Obvious' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-38.jpg', app: 'Indeed' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-39.jpg', app: 'Langdock' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-40.jpg', app: 'Langdock' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-41.jpg', app: 'Firecrawl' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-42.jpg', app: 'Profound' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-43.jpg', app: 'Adaline' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-44.jpg', app: 'Sentry' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-45.jpg', app: 'ClickUp' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-46.jpg', app: 'YouTube Music' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-47.jpg', app: 'Remote' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-48.jpg', app: 'Perplexity' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-49.jpg', app: 'Visual Electric' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-50.jpg', app: 'Mixpanel' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-51.jpg', app: 'Todoist' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-52.jpg', app: 'Rox' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-53.jpg', app: 'Peec AI' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-54.jpg', app: 'Neon' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-55.jpg', app: 'Apollo' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-56.jpg', app: 'Origin' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-58.jpg', app: 'Ferndesk' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-59.jpg', app: 'Etsy' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-60.jpg', app: 'Ditto' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-62.jpg', app: 'Vercel' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-63.jpg', app: 'Base44' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-64.jpg', app: 'Resend' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-65.jpg', app: 'ManyChat' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-66.jpg', app: 'Cosmos' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-67.jpg', app: 'Obvious' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-68.jpg', app: 'Laravel Cloud' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-69.jpg', app: 'Indeed' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-70.jpg', app: 'Vercel' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-71.jpg', app: 'Felt' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-72.jpg', app: 'Base44' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-73.jpg', app: 'Fireflies' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-75.jpg', app: 'Laravel Cloud' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-76.jpg', app: 'Zoho CRM' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-77.jpg', app: 'Obvious' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-78.jpg', app: 'Quicken' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-79.jpg', app: 'Workable' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-80.jpg', app: 'Juicebox' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-81.jpg', app: 'Workable' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-83.jpg', app: 'Obvious' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-84.jpg', app: 'Juicebox' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-85.jpg', app: 'Juicebox' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-89.jpg', app: 'Turo' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-90.jpg', app: 'Cloudflare' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-91.jpg', app: 'Cloudflare' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-92.jpg', app: 'Obvious' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-94.jpg', app: 'Langdock' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-95.jpg', app: 'komoot' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-96.jpg', app: 'Indeed' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-97.jpg', app: 'Langdock' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-99.jpg', app: 'Zoho CRM' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-100.jpg', app: 'Juicebox' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-101.jpg', app: 'Cloudflare' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-102.jpg', app: 'Arcade' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-103.jpg', app: 'Indeed' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-107.jpg', app: 'Ditto' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-108.jpg', app: 'Workable' },
  { src: 'assets/blog/visual-identity/moodboard/moodboard-109.jpg', app: 'Langdock' },
];
